apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--requirepass", $(REDIS_PASS)]
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: nest-secret
                  key: REDIS_PASS
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}   # 缓存数据，使用临时卷即可
