# 该文件目的是定义一个 Deployment 对象，
# Deployment 是 Kubernetes 中用于管理 Pod 副本的对象，
# 可以确保指定数量的 Pod 在任何时候都在运行，并提供滚动更新等功能。

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: nest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nest-secret
                  key: MONGO_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nest-secret
                  key: MONGO_ROOT_PASS
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc