# 该文件目的是定义一个 Service 对象，
# Service 是 Kubernetes 中用于暴露应用的对象，
# 可以将一组 Pod 作为一个服务对外提供访问，支持负载均衡和服务发现等功能。

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: nest-demo
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017