# 该文件目的是定义一个 Secret 对象，
# Secret 是 Kubernetes 中用于存储敏感数据的对象，
# 如密码、密钥等，可以在 Pod 中以环境变量或文件的形式使用。

apiVersion: v1
kind: Secret
metadata:
  name: nest-secret
  namespace: nest-demo
type: Opaque
stringData:
  # stringData 会自动 base64，不用手动编码
  MONGO_ROOT_USER: root
  MONGO_ROOT_PASS: Password01!
  MONGODB_URI: mongodb://root:Password01!@mongodb-svc:27017/nest-demo?authSource=admin
  RABBITMQ_USER: admin
  RABBITMQ_PASS: Password01!
  RABBITMQ_URL: amqp://admin:Password01!@rabbitmq-svc:5672
  REDIS_PASS: Password01!
  # JwtModule 默认用 HS256（对称算法），secretOrPrivateKey 必须是普通字符串。RSA PEM 私钥是非对称算法（RS256）专用的，两者不兼容。如果要用 RSA 私钥，需要在 JwtModule.registerAsync 里加 algorithm: 'RS256' 且同时配置公钥用于验证——学习阶段没必要，直接用字符串即可。
  JWT_SECRET: "nest-demo-jwt-secret-2026"
  ADMIN_INIT_PASSWORD: Password01!
  ADMIN_INIT_EMAIL: admin@example.com