apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nest-demo-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001   # TCP 微服务端口
          envFrom:
            - configMapRef:
                name: nest-config
            - secretRef:
                name: nest-secret
