apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: nest-demo
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP   # 仅集群内部可访问（gateway 通过 TCP 连接）
